// This GUI file is generated by guibuilder version 4.2.1
//////////
f=figure('figure_position',[624,-862],'figure_size',[900,600],'auto_resize','on','background',[33],'figure_name','Figure n°%d','dockable','off','infobar_visible','off','toolbar_visible','off','menubar_visible','off','default_axes','on','visible','off');
//////////
handles.dummy = 0;

handles.img=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0122167,0.9464627,0.0817241,0.0497132],'Relief','default','SliderStep',[0.01,0.1],'String','Image','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','img','Callback','img_callback(handles)')
handles.his=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0135468,0.8986616,0.1117241,0.0478011],'Relief','default','SliderStep',[0.01,0.1],'String','Histogram','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','his','Callback','his_callback(handles)')
f.visible = "on";


//////////
// Callbacks are defined as below. Please do not delete the comments as it will be used in coming version
//////////

function photo_callback(handles)
    
endfunction


function img_callback(handles)
    img_path = uigetfile(["*.png";"*.bmp"], "C:/Users/Amir/Desktop/paris8/dev_logiciel_libre/test_images","Choose a file");
    disp(img_path);
    img = imread(img_path);
    
    disp(size(img));
    disp(img);
    //if img then
    imshow(img);
    
    //else
        //messagebox("No file selected", "Error", "error", "modal");
        //return
    //end
endfunction


function his_callback(handles)
    img_path = uigetfile(['*.tiff';'*.bmp'], "C:/Users/Amir/Desktop/paris8/dev_logiciel_libre/test_images","Choose a file");
    disp(img_path);
    x=imread(img_path);
    [l,c] = size(x);
    // Calcul de l'histogramme
    h=zeros(1,256)
    for i = 1:l
        for j = 1:c
            h(x(i,j)+1)=h(x(i,j)+1)+1
        end
    end
    subplot(1,3,1), plot(h);
    subplot(1,3,2), bar(imhist(x));
    subplot(1,3,3), imshow(x);
endfunction


function flt_callback(handles)
//Write your callback for  flt  here

endfunction


function gus_callback(handles)
//Write your callback for  gus  here

endfunction


function slt_callback(handles)
    //img_path = uigetfile(['*.bmp';'*.tiff';'*.png'], "C:/Users/Amir/Desktop/paris8/dev_logiciel_libre/test_images","Choose a file");
    disp(handles);
    
    x=imread(handles);
    z = imnoise(x, 'salt & pepper');
    // Filtre moyenneur
    k=[1/9 1/9 1/9; 1/9 1/9 1/9; 1/9 1/9 1/9]
    res2 = filter2(z,k);
    res2=uint8(res2);
 
    imshow(res2);

endfunction


